version: '3'

services:
  webserver:
    image: webserver
    container_name: webserver
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - nginx_network  
  test:
    image: test
    container_name: test
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    build:
      context: ./jenkins
    volumes:
      # - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home //bikin permanent data-datanya
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx_network
  
networks:
  nginx_network:
    name: nginx_network
    driver: bridge