version: '3'

services:
  web:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    # Mapping of container port to host
    ports:
      - "5000:5000"
    volumes:
     - .:/app