version: '3'

services:
  webserver:
    image: webserver
    container_name: webserver
    build:
      context: ./nginx
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - nginx_network
  
  api:
    tty: true
    image: haidinata/api:v1
    container_name: api
    depends_on:
      - db
    environment:
      POSTGRES_DB: djangoapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: on-failure
    networks:
        - nginx_network
  
  db:
    image: haidinata/db:v1
    container_name: db
    restart: always
    ports:
      - 5432:5432
    networks:
      - nginx_network
  
  test:
    image: test
    container_name: test
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    build:
      context: ./jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx_network
  
networks:
  nginx_network:
    name: nginx_network
    driver: bridge