version: '3'

services:

  webServer:
    image: nginx:1.17.10
    container_name: webServer
    depends_on:
        - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3200:3200

  api:
    image: api
    container_name: api
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:5001
    ports:
      - 5001:5001
    restart: on-failure

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    # volumes: 
    #   - db:/var/lib/postgresql/data