# syntax=docker/dockerfile:1
FROM python:3

RUN apt-get update & apt-get install git

COPY . .

# COPY ./app/requirements.txt requirements.txt

# insert into env
# RUN .\env\Scripts\activate 
RUN python -m pip install --upgrade pip
RUN cd ./app
RUN pip install -r ./app/requirements.txt

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
