pipeline {
    agent { docker { image 'python:3.9' image 'postgres:14.1-alpine' } }
    stages {
        stage('Build') { 
            steps {
                echo "build app"
                sh 'pip install -r app/requirements.txt'
            }
        }
        stage('Test') { 
            steps {
                echo "test app"
                sh 'python --version'
                sh 'python app/manage.py test ./app'
            }
        }
        stage('Deploy') { 
            steps {
                echo "deploy app"
            }
        }
    }
}